name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-3.6:
    runs-on: ubuntu-latest

    env:
      python_version: "3.6"
      tag: ${{ env.python_version }}-slim
      CI_REGISTRY_IMAGE_4: ${{ env.CI_REGISTRY_IMAGE }}-4
      CI_REGISTRY_IMAGE_5: ${{ env.CI_REGISTRY_IMAGE }}-5

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u "${{ env.CI_REGISTRY_USER }}" -p "${{ env.CI_REGISTRY_PASSWORD }}" ${{ env.CI_REGISTRY }}
    - name: Log
      run: echo Running on default branch ${{ env.CI_DEFAULT_BRANCH }} - tag = ${{ env.tag }}
    - name: Docker build for AstroPy 4
      run: docker build --pull -t "${{ env.CI_REGISTRY_IMAGE_4 }}:${{ env.tag }}" --network host -f docker/${{ env.python_version }}/slim/Dockerfile-4 docker/${{ env.python_version }}/slim/
    - name: Docker push AstroPy 4
      run: docker push "${{ env.CI_REGISTRY_IMAGE_4 }}:${{ env.tag }}"
    - name: Docker cleanup AstroPy 4
      run: docker rmi "${{ env.CI_REGISTRY_IMAGE_4 }}:${{ env.tag }}"
    - name: Docker build for AstroPy 5
      run: docker build --pull -t "${{ env.CI_REGISTRY_IMAGE_5 }}:${{ env.tag }}" --network host -f docker/${{ env.python_version }}/slim/Dockerfile-5 docker/${{ env.python_version }}/slim/
    - name: Docker push AstroPy 5
      run: docker push "${{ env.CI_REGISTRY_IMAGE_5 }}:${{ env.tag }}"
    - name: Docker cleanup AstroPy 5
      run: docker rmi "${{ env.CI_REGISTRY_IMAGE_5 }}:${{ env.tag }}"
