name: OpenCADC AstroPy Docker CI

on:
  pull_request:
  push:
  release:

jobs:
  #
  # Package jobs
  #
  package-3_13:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      name: astropy
      version: '3.13'
      flavour: slim

  package-3_14:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      name: astropy
      version: '3.14'
      flavour: slim
#
# End Package Jobs
#
